#!/usr/bin/tclsh
# source  /mnt/c/Users/dgall/OpenROAD-flow/setup_env.sh

# Command line parameters: bw - bit width, l - n° approximate bits, type of AMA {1..5}
# If type is null all AMA's types are executing

#ToDO: CONFIGURE THESE PARAMETERS!
set AUGER_DIRECTORY "/mnt/c/Users/dgall/AUGER"
set OpenROAD_DIRECTORY "/mnt/c/Users/dgall/OpenROAD-flow"
set PLATFORM "nangate45"

# #########################################################

puts "Starting"
set DESIGN_TYPE "AMA"
set DESIGN_AUGER_NAME "AMA"
set DIR_NAME "ama"

set bw [lindex $argv 0]
set l [lindex $argv 1]
set type [lindex $argv 2]
set max 1

if {$type eq ""} {
    set type 1
    set max 5
}

for {set i 0} {$i<$max} {incr i} {
    puts "Executing ${DESIGN_TYPE}${type}"
    cd $AUGER_DIRECTORY
    puts "Runnig AUGER for $DESIGN_AUGER_NAME -bw $bw -l $l"
    # Exec Auger
    try {exec ./AUGER -a ${DESIGN_AUGER_NAME}$type -bw $bw -l $l -gen} on error {msg} {puts $msg}
    file mkdir $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}$type-$bw-$l
    file mkdir $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE/${DIR_NAME}$type-$bw-$l
    puts "Coping src"
    # Copy all files generated by AUGER in the correct openROAD directory
    foreach f [glob -directory ./ALGO/ADDERS/${DESIGN_AUGER_NAME}$type/SRC -nocomplain *] {
        file copy -force $f $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}$type-$bw-$l
    }
    cd $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE

    puts "Coping config"
    # Create all configuration files for openROAD
    # Copy costraints.sdc, rules.json and area data from gcd design
    foreach f [glob -directory ../gcd -nocomplain *] {
        file copy -force $f ./${DIR_NAME}$type-$bw-$l
    }
    set fp [open ./${DIR_NAME}$type-$bw-$l/config.mk w]
    puts $fp "export DESIGN_NICKNAME = ${DIR_NAME}$type-$bw-$l"
    puts $fp "export DESIGN_NAME = LPA"
    puts $fp "export PLATFORM = $PLATFORM"
    puts $fp "export VERILOG_FILES = \$(wildcard ./designs/src/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/*.v)"
    puts $fp "export SDC_FILE = ./designs/\$(PLATFORM)/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/constraint.sdc"
    puts $fp "export DIE_AREA = 0 0 100.13 100.8"
    puts $fp "export CORE_AREA = 10.07 11.2 90.25 91"
    close $fp
    cd $OpenROAD_DIRECTORY/flow

    # Exec openROAD flow
    puts "Runnig openROAD..."
    try {exec make DESIGN_CONFIG=./designs/$PLATFORM/$DESIGN_TYPE/${DIR_NAME}$type-$bw-$l/config.mk} on error {msg} {
        puts $msg
    }
    incr type
}   

puts "Finish"
