#!/usr/bin/tclsh
#source  /mnt/c/Users/dgall/OpenROAD-flow/setup_env.sh

# Command line parameters: bw - bit width, r, p

#ToDO: CONFIGURE THESE PARAMETERS!
set AUGER_DIRECTORY "/mnt/c/Users/dgall/AUGER"
set OpenROAD_DIRECTORY "/mnt/c/Users/dgall/OpenROAD-flow"
set PLATFORM "nangate45"

# #########################################################

puts "Starting"

set DESIGN_TYPE "GeAr"
set DESIGN_AUGER_NAME "GeAr"
set DIR_NAME "gear"

set bw [lindex $argv 0] 
set r [lindex $argv 1]
set p [lindex $argv 2]
set l $r+$p

cd $AUGER_DIRECTORY

puts "Runnig AUGER for $DESIGN_TYPE -bw $bw -l $l -r $r -p $p"

try {exec ./AUGER -a ${DESIGN_AUGER_NAME} -bw $bw -l $l -r $r -p $p -gen} on error {msg} {puts $msg}

puts "Creating directoris"
file mkdir $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}-$bw-$r-$p
file mkdir $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE/${DIR_NAME}-$bw-$r-$p

puts "Coping src"
# Copy all files generated by AUGER in the correct openROAD directory
foreach f [glob -directory ./ALGO/ADDERS/${DESIGN_AUGER_NAME}/SRC -nocomplain *] {
    file copy -force $f $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}-$bw-$r-$p
}

cd $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE

puts "Coping config"
# Create all configuration files for openROAD
# Copy costraints.sdc, rules.json and area data from gcd design
foreach f [glob -directory ../gcd -nocomplain *] {
    file copy -force $f ./$DIR_NAME-$bw-$r-$p
}
set fp [open ./$DIR_NAME-$bw-$r-$p/config.mk w]
puts $fp "export DESIGN_NICKNAME = ${DIR_NAME}-$bw-$r-$p"
puts $fp "export DESIGN_NAME = GeAr"
puts $fp "export PLATFORM = $PLATFORM"
puts $fp "export VERILOG_FILES = \$(wildcard ./designs/src/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/*.v)"
puts $fp "export SDC_FILE = ./designs/\$(PLATFORM)/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/constraint.sdc"

puts $fp "export DIE_AREA = 0 0 100.13 100.8"
puts $fp "export CORE_AREA = 10.07 11.2 90.25 91"
close $fp

cd $OpenROAD_DIRECTORY/flow

# Exec openROAD flow
puts "Runnig openROAD... 1/1"
try {exec make DESIGN_CONFIG=./designs/$PLATFORM/$DESIGN_TYPE/$DIR_NAME-$bw-$r-$p/config.mk} on error {msg} {
    puts $msg
}
puts "Finish"
