#!/usr/bin/tclsh
# source  /mnt/c/Users/dgall/OpenROAD-flow/setup_env.sh

# Command line parameters: bw - bit width

#ToDO: CONFIGURE THESE PARAMETERS!
set AUGER_DIRECTORY "/mnt/c/Users/dgall/AUGER"
set OpenROAD_DIRECTORY "/mnt/c/Users/dgall/OpenROAD-flow"
set PLATFORM "nangate45"

# #########################################################

puts "Starting"

set DESIGN_TYPE "RoBA"
set DESIGN_AUGER_NAME "RoBa"
set DIR_NAME "roba"

set bw [lindex $argv 0]

cd $AUGER_DIRECTORY

puts "Runnig AUGER for $DESIGN_TYPE -bw $bw"

try {exec ./AUGER -m ${DESIGN_AUGER_NAME} -bw $bw -gen} on error {msg} {puts $msg}

puts "Creating directoris"
file mkdir $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}-$bw
file mkdir $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE/${DIR_NAME}-$bw

puts "Coping src"
# Copy all files generated by AUGER in the correct openROAD directory
foreach f [glob -directory ./ALGO/MULTIPLIERS/${DESIGN_AUGER_NAME}/SRC -nocomplain *] {
    file copy -force $f $OpenROAD_DIRECTORY/flow/designs/src/$DESIGN_TYPE/${DIR_NAME}-$bw
}

cd $OpenROAD_DIRECTORY/flow/designs/$PLATFORM/$DESIGN_TYPE

puts "Coping config"
# Copy costraints.sdc and area data from jepg design
foreach f [glob -directory ../jpeg -nocomplain *] {
    file copy -force $f ./$DIR_NAME-$bw
}
set fp [open ./$DIR_NAME-$bw/config.mk w]
puts $fp "export DESIGN_NICKNAME = ${DIR_NAME}-$bw"
puts $fp "export DESIGN_NAME = RoBa"
puts $fp "export PLATFORM = $PLATFORM"
puts $fp "export VERILOG_FILES = \$(wildcard ./designs/src/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/*.v)"
puts $fp "export SDC_FILE = ./designs/\$(PLATFORM)/$DESIGN_TYPE/\$(DESIGN_NICKNAME)/constraint.sdc"
puts $fp "export DIE_AREA = 0 0 2400.08 2399.6"
puts $fp "export CORE_AREA = 10.07 9.8 2379.94 2380"
close $fp

cd $OpenROAD_DIRECTORY/flow

# Exec openROAD flow
puts "Runnig openROAD... 1/1"
try {exec make DESIGN_CONFIG=./designs/$PLATFORM/$DESIGN_TYPE/$DIR_NAME-$bw/config.mk} on error {msg} {
    puts $msg
}

puts "Finish"